 File "scripts/load_data/data_writer_merger.py", line 112, in <module>
    merge_files(source_dir, merged_fpath)
  File "scripts/load_data/data_writer_merger.py", line 32, in merge_files
    base = concat_two_dicts(base,d)
  File "/hcp/home/jwkim2/atlas_dl/scripts/load_data/util.py", line 42, in concat_two_dicts
    base[k] = np.vstack((base[k], addition[k]))
  File "<__array_function__ internals>", line 6, in vstack
  File "/hcp/home/jwkim2/.local/lib/python3.6/site-packages/numpy/core/shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5990 and the array at index 1 has size 11735

